=== sissaschool/xmlschema/xmlschema/tests/test_cases/examples/collection/collection3bis.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://example.com/ns/collection"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://example.com/ns/collection">
  <xs:element name="collection">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="author" type="personType" maxOccurs="unbounded">
          <xs:key name="author_dn">
            <xs:selector xpath="."/>
            <xs:field xpath="@dn"/>
          </xs:key>
        </xs:element>
        <xs:element name="object" type="objType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    <xs:keyref name="author_dn_ref" refer="author_dn">
      <xs:selector xpath="object"/>
      <xs:field xpath="author"/>
    </xs:keyref>
  </xs:element>
  <xs:element name="person" type="personType"/>
  <xs:complexType name="personType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="born" type="xs:date"/>
      <xs:element name="dead" type="xs:date" minOccurs="0"/>
      <xs:element name="qualification" type="xs:string" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="dn" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="objType">
    <xs:sequence>
      <xs:element name="position" type="xs:int"/>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="year" type="xs:gYear"/>
      <xs:element name="author" type="xs:string"/>
      <xs:element name="estimation" type="xs:decimal" minOccurs="0"/>
      <xs:element name="characters" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="person" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="available" type="xs:boolean" use="required"/>
  </xs:complexType>
</xs:schema>

=== sissaschool/xmlschema/tests/test_cases/examples/collection/collection3bis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Invalid because collection3bis.xsd puts the xs:key on single element and
the 2nd author overrides the first. -->
<col:collection xmlns:col="http://example.com/ns/collection"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://example.com/ns/collection collection3bis.xsd">
	<author dn="PAR">
		<name>Pierre-Auguste Renoir</name>
		<born>1841-02-25</born>
		<dead>1919-12-03</dead>
		<qualification>painter</qualification>
	</author>
	<author dn="JM">
		<name>Joan Mir√≥</name>
		<born>1893-04-20</born>
		<dead>1983-12-25</dead>
		<qualification>painter, sculptor and ceramicist</qualification>
	</author>
	<object id="b0836217462" available="true">
		<position>1</position>
		<title>The Umbrellas</title>
		<year>1886</year>
		<author>PAR</author>
        <estimation>10000.00</estimation>
	</object>
	<object id="b0836217463" available="true">
		<position>2</position>
		<title/>
		<year>1925</year>
		<author>JM</author>
	</object>
</col:collection>
