=== sissaschool/xmlschema/tests/test_cases/features/decoder/simple-types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="ns" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="ns" >
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="decimal_value" type="Decimal_9_5" maxOccurs="unbounded"/>
                <xs:element name="celsiusBodyTemp" type="celsiusBodyTemp" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="certification" type="year_attr_string_75" maxOccurs="unbounded"/>
                <xs:element name="menÃ¹" type="xs:string"/>
                <xs:element name="complex_boolean" type="TYPE_ATTR_BOOLEAN" minOccurs="0" maxOccurs="4"/>
                <xs:element name="simple_boolean" type="xs:boolean" minOccurs="0" maxOccurs="4"/>
                <xs:element name="date_and_time" type="xs:dateTime" minOccurs="0"/>
                <xs:element name="name" type="none_empty_string" minOccurs="0"/>
                <xs:element name="config" type="config" minOccurs="0"/>
                <xs:element name="dateTimeWithTZOffset" type="xs:dateTime" minOccurs="0"/>
                <xs:element name="duration" type="xs:duration" minOccurs="0"/>
                <xs:element name="hexbin" type="hexCode" minOccurs="0" />
                <xs:element name="base64bin" type="base64Code" minOccurs="0" />
                <xs:element name="list_of_floats" type="list_of_floats" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="Decimal_9_5">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="9"/>
            <xs:fractionDigits value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name='celsiusBodyTemp'>
        <xs:restriction base='xs:decimal'>
            <xs:totalDigits value='4'/>
            <xs:fractionDigits value='1'/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="string_75">
        <xs:restriction base="xs:string">
            <xs:maxLength value="75"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="year_attr_string_75">
        <xs:simpleContent>
            <xs:extension base="string_75">
                <xs:attribute name="Year" type="xs:integer"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="TYPE_ATTR_BOOLEAN">
        <xs:simpleContent>
            <xs:extension base="xs:boolean">
                <xs:attribute name="Type" type="xs:integer"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- List types -->
    <xs:simpleType name="list_of_strings">
        <xs:list itemType="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="list_of_integers">
        <xs:list itemType="xs:integer"/>
    </xs:simpleType>

    <xs:simpleType name="list_of_floats">
        <xs:list itemType="xs:float"/>
    </xs:simpleType>

    <xs:simpleType name="list_of_booleans">
        <xs:list itemType="xs:boolean"/>
    </xs:simpleType>

    <!-- Union types -->
    <xs:simpleType name="integer_or_float">
        <xs:union memberTypes="xs:integer xs:float"/>
    </xs:simpleType>

    <xs:simpleType name="integer_or_string">
        <xs:union memberTypes="xs:integer xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="boolean_or_integer_or_string">
        <xs:union memberTypes="xs:boolean xs:integer xs:string"/>
    </xs:simpleType>

    <!-- For testing issue #63 -->
    <xs:simpleType name='hexCode'>
        <xs:restriction base='xs:hexBinary'>
            <xs:length value='4'/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name='base64Code'>
        <xs:restriction base='xs:base64Binary'>
            <xs:minLength value='3'/>
            <xs:maxLength value='8'/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name='base64Length4'>
        <xs:restriction base='xs:base64Binary'>
            <xs:length value='4'/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name='base64Length5'>
        <xs:restriction base='xs:base64Binary'>
            <xs:length value='5'/>
        </xs:restriction>
    </xs:simpleType>

    <!-- For testing issue #64 -->
    <xs:simpleType name="none_empty_string">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NameType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="255"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- For testing issue #83 -->
    <xs:simpleType name="config">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
            <xs:pattern value="(word|other)|(alternative)"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Issue #103 -->
    <xs:simpleType name="myType">
        <xs:union memberTypes="typeA typeB"/>
    </xs:simpleType>

    <xs:simpleType name="typeA">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.0"/>
            <xs:maxInclusive value="100.0"/>
            <xs:fractionDigits value="3"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typeB">
        <xs:restriction base="xs:string">
            <xs:pattern value="NaN"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- For testing encoding -->
    <xs:simpleType name="mdate">
        <xs:restriction base="xs:date">
            <xs:minInclusive value="2000-01-01" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="enum1">
        <xs:restriction base="xs:string">
            <xs:enumeration value="one"/>
            <xs:enumeration value="two"/>
            <xs:enumeration value="three"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== sissaschool/xmlschema/tests/test_cases/features/decoder/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:data xmlns:ns="ns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="ns ./simple-types.xsd">
    <decimal_value>1</decimal_value>
    <certification Year="1999">ISO-9001</certification>
    <certification Year="2009">ISO-27001</certification>
    <menù>baccalà mantecato</menù>
    <complex_boolean Type="2">true</complex_boolean>
    <complex_boolean Type="1">false</complex_boolean>
    <complex_boolean>true</complex_boolean>
    <complex_boolean>false</complex_boolean>
    <simple_boolean>true</simple_boolean>
    <simple_boolean>false</simple_boolean>
    <date_and_time>2020-03-05T23:04:10.047</date_and_time>
    <hexbin>AABBCCDD</hexbin>
    <list_of_floats>INF -INF</list_of_floats>
    <qname>ns:foo</qname>
</ns:data>
